# Generated by Django 4.1 on 2022-08-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.PositiveIntegerField()),
                ('fecha_de_nacimiento', models.DateField()),
                ('dni', models.PositiveIntegerField()),
                ('numero_de_telefono', models.PositiveIntegerField()),
                ('nacionalidad', models.CharField(max_length=10)),
                ('parentesco', models.CharField(max_length=10)),
            ],
        ),
    ]
